apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app # Link entre o service e o deployment
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer